#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import re

# Read English source file
with open('/Users/merdana/AndroidStudioProjects/eduvesta/src/assets/lang/en.json', 'r', encoding='utf-8') as f:
    en_data = json.load(f)

# Read existing Turkmen translations
with open('/Users/merdana/AndroidStudioProjects/eduvesta/src/assets/lang/tk.json', 'r', encoding='utf-8') as f:
    tk_data = json.load(f)

# Translation dictionary for common terms
translations = {
    # Authentication & Login
    "Login": "Giriş",
    "Log in": "Gir",
    "Username": "Ulanyjy ady",
    "Password": "Parol",
    "Email": "E-poçta",
    "Sign up": "Ýazyl",
    "Sign in": "Gir",
    "Logout": "Çyk",
    "Log out": "Çyk",

    # Common actions
    "Submit": "Tabşyr",
    "Save": "Sakla",
    "Cancel": "Ýatyr",
    "Delete": "Poz",
    "Remove": "Aýyr",
    "Edit": "Üýtget",
    "Add": "Goş",
    "Create": "Döret",
    "Update": "Täzele",
    "Upload": "Ýükle",
    "Download": "Göçürip al",
    "Send": "Iber",
    "Search": "Gözle",
    "Filter": "Süzgüç",
    "Sort": "Tertiple",
    "Back": "Yza",
    "Next": "Indiki",
    "Previous": "Öňki",
    "Continue": "Dowam et",
    "Close": "Ýap",
    "Open": "Aç",
    "Refresh": "Täzele",
    "Reload": "Gaýtadan ýükle",
    "Retry": "Gaýtadan synanyş",
    "Try again": "Gaýtadan synanyş",
    "View": "Gör",
    "Show": "Görkez",
    "Hide": "Gizle",
    "Expand": "Giňelt",
    "Collapse": "Ýygyşdyr",
    "Select": "Saýla",
    "Choose": "Saý",
    "Copy": "Göçür",
    "Paste": "Goý",
    "Cut": "Kes",
    "Confirm": "Tassykla",
    "Yes": "Hawa",
    "No": "Ýok",
    "OK": "Bolýar",
    "Done": "Taýýar",
    "Finish": "Tamamla",
    "Complete": "Tamamla",
    "Start": "Başla",
    "Stop": "Dur",
    "Pause": "Arakesme et",
    "Resume": "Dowam et",
    "Skip": "Geç",
    "Clear": "Arassala",
    "Reset": "Täzeden",
    "Apply": "Ulanyş",
    "Dismiss": "Ret et",
    "Accept": "Kabul et",
    "Decline": "Ret et",
    "Enable": "Aç",
    "Disable": "Ýap",
    "Activate": "Işjeňleşdir",
    "Deactivate": "Işden çykar",

    # Status & messages
    "Loading": "Ýüklenýär",
    "Loading...": "Ýüklenýär...",
    "Please wait": "Garaşyň",
    "Processing": "Işlenilýär",
    "Sending": "Iberilýär",
    "Saving": "Saklanýar",
    "Success": "Üstünlik",
    "Error": "Ýalňyşlyk",
    "Warning": "Duýduryş",
    "Notice": "Habar",
    "Info": "Maglumat",
    "Information": "Maglumat",
    "Help": "Kömek",
    "Settings": "Sazlamalar",
    "Options": "Saýlawlar",
    "Preferences": "Ileri tutmalar",
    "Configuration": "Sazlama",

    # Education specific
    "Course": "Kurs",
    "Courses": "Kurslar",
    "Teacher": "Mugallym",
    "Student": "Okuwçy",
    "Students": "Okuwçylar",
    "Assignment": "Tabşyryk",
    "Assignments": "Tabşyryklar",
    "Grade": "Baha",
    "Grades": "Bahalar",
    "Quiz": "Synag",
    "Quizzes": "Synaglar",
    "Exam": "Ekzamen",
    "Test": "Test",
    "Lesson": "Sapak",
    "Lessons": "Sapaklar",
    "Module": "Modul",
    "Activity": "Işjeňlik",
    "Activities": "Işjeňlikler",
    "Forum": "Forum",
    "Discussion": "Pikir alyşma",
    "Chat": "Söhbetdeşlik",
    "Message": "Habar",
    "Messages": "Habarlar",
    "Notification": "Bildiriş",
    "Notifications": "Bildirişler",
    "Calendar": "Kalendar",
    "Event": "Waka",
    "Events": "Wakalar",
    "Deadline": "Möhlet",
    "Due date": "Tabşyrmaly senesi",
    "Submit assignment": "Tabşyrygy tabşyr",
    "Submission": "Tabşyrylan",
    "Feedback": "Teswir",
    "Comment": "Teswir",
    "Comments": "Teswirler",
    "Attachment": "Goşundy",
    "Attachments": "Goşundylar",
    "File": "Faýl",
    "Files": "Faýllar",
    "Folder": "Papka",
    "Upload file": "Faýl ýükle",
    "Download file": "Faýl göçürip al",
    "Content": "Mazmun",
    "Description": "Düşündiriş",
    "Summary": "Gysgaça",
    "Details": "Jikme-jiklikler",
    "Overview": "Syn",
    "Progress": "Öňegidişlik",
    "Completion": "Tamamlama",
    "Status": "Ýagdaý",
    "Type": "Görnüş",
    "Category": "Kategoriýa",
    "Categories": "Kategoriýalar",
    "Topic": "Tema",
    "Section": "Bölüm",
    "Chapter": "Bap",
    "Page": "Sahypa",
    "Pages": "Sahypalar",
    "Book": "Kitap",
    "Resource": "Serişde",
    "Resources": "Serişdeler",
    "Link": "Baglanyşyk",
    "URL": "URL",
    "Site": "Sahypa",
    "Website": "Web sahypa",
    "Dashboard": "Panel",
    "Home": "Baş sahypa",
    "Profile": "Profil",
    "Account": "Hasap",
    "User": "Ulanyjy",
    "Users": "Ulanyjylar",
    "Group": "Topar",
    "Groups": "Toparlar",
    "Name": "Ady",
    "First name": "Ady",
    "Last name": "Familiýasy",
    "Full name": "Doly ady",
    "Date": "Sene",
    "Time": "Wagt",
    "Duration": "Dowamlylygy",
    "From": "Başlangyjy",
    "To": "Soňy",
    "Start date": "Başlanýan senesi",
    "End date": "Gutarýan senesi",
    "Created": "Döredilen",
    "Modified": "Üýtgedilen",
    "Updated": "Täzelenen",
    "Version": "Wersiýa",
    "Size": "Ululygy",
    "Language": "Dil",
    "Country": "Ýurt",
    "City": "Şäher",
    "Address": "Salgy",
    "Phone": "Telefon",
    "Image": "Surat",
    "Picture": "Surat",
    "Photo": "Surat",
    "Video": "Wideo",
    "Audio": "Ses",
    "Media": "Metbugatlar",
    "Required": "Hökmany",
    "Optional": "Meýletin",
    "Public": "Açyk",
    "Private": "Gizlin",
    "Hidden": "Gizlenen",
    "Visible": "Görünýän",
    "Available": "Elýeterli",
    "Unavailable": "Elýeterli däl",
    "Enabled": "Açyk",
    "Disabled": "Ýapyk",
    "Active": "Işjeň",
    "Inactive": "Işjeň däl",
    "Online": "Onlaýn",
    "Offline": "Oflaýn",
    "Connected": "Birikdirilen",
    "Disconnected": "Bölünýän",
    "All": "Ählisi",
    "None": "Hiç",
    "Any": "Islendik",
    "Other": "Beýleki",
    "More": "Giňişleýin",
    "Less": "Az",
    "New": "Täze",
    "Old": "Köne",
    "Recent": "Soňky",
    "Latest": "Iň täze",
    "Total": "Jemi",
    "Count": "San",
    "Number": "San",
    "Title": "Ady",
    "Subject": "Tema",
    "Author": "Awtor",
    "Publisher": "Neşirçi",
    "License": "Ygtyýarnama",
    "Copyright": "Awtorlyk hukugy",
    "Tag": "Belgi",
    "Tags": "Bellikler",
    "Keyword": "Açar söz",
    "Keywords": "Açar sözler",
    "Icon": "Nyşan",
    "Logo": "Logotip",
    "Banner": "Banner",
    "Header": "Ýokarky",
    "Footer": "Aşaky",
    "Sidebar": "Gapdal paneli",
    "Menu": "Menýu",
    "Navigation": "Nawigasiýa",
    "Breadcrumb": "Ugur",
    "Tab": "Bellik",
    "Tabs": "Bellikler",
    "Button": "Düwme",
    "Checkbox": "Bellik ýuluny",
    "Radio": "Radio düwme",
    "Dropdown": "Aşakdan açylýan",
    "List": "Sanaw",
    "Table": "Tablisa",
    "Form": "Forma",
    "Field": "Meýdan",
    "Label": "Bellik",
    "Value": "Bahasy",
    "Default": "Deslapky",
    "Custom": "Ýörite",
    "Advanced": "Ösen",
    "Basic": "Esasy",
    "General": "Umumy",
    "Specific": "Kesgitlenen",
    "Permission": "Rugsat",
    "Permissions": "Rugsatlar",
    "Role": "Rol",
    "Roles": "Rollar",
    "Access": "Girmek",
    "Security": "Howpsuzlyk",
    "Privacy": "Gizlinlik",
    "Terms": "Şertler",
    "Conditions": "Şertler",
    "Agreement": "Ylalaşyk",
    "Policy": "Syýasat",
    "About": "Barada",
    "Contact": "Habarlaşmak",
    "Support": "Goldaw",
    "Feedback": "Teswir",
    "Report": "Hasabat",
    "Issue": "Mesele",
    "Bug": "Ýalňyşlyk",
    "Feature": "Aýratynlyk",
    "Request": "Haýyş",
    "Suggestion": "Teklip",
    "Rating": "Baha",
    "Review": "Syn",
    "Share": "Paýlaş",
    "Export": "Eksport et",
    "Import": "Import et",
    "Print": "Çap et",
    "Preview": "Deslapky syn",
    "Fullscreen": "Doly ekran",
    "Zoom": "Ulalt",
    "Rotate": "Aýlan",
    "Flip": "Öwür",
    "Crop": "Kes",
    "Resize": "Ululygyny üýtget",
    "Format": "Format",
    "Quality": "Hil",
    "Resolution": "Kesgitlilik",
    "Color": "Reňk",
    "Background": "Fon",
    "Foreground": "Öň plan",
    "Border": "Çäk",
    "Margin": "Çetki",
    "Padding": "Içki giňlik",
    "Width": "Ini",
    "Height": "Beýikligi",
    "Left": "Çep",
    "Right": "Sag",
    "Top": "Ýokary",
    "Bottom": "Aşak",
    "Center": "Merkez",
    "Middle": "Orta",
    "Align": "Deňleşdir",
    "Position": "Ýerleşişi",
    "Layout": "Tertibi",
    "Style": "Stili",
    "Theme": "Tema",
    "Font": "Şrift",
    "Text": "Tekst",
    "Paragraph": "Abzas",
    "Heading": "Sözbaşy",
    "Bold": "Galyň",
    "Italic": "Egilen",
    "Underline": "Aşaky çyzgy",
    "Strikethrough": "Üsti çyzylan",
    "Subscript": "Aşaky ýazgy",
    "Superscript": "Ýokarky ýazgy",
    "Bullet": "Nokatly sanaw",
    "Numbered": "Sanly sanaw",
    "Indent": "Çekinme",
    "Outdent": "Çekinmäni aýyr",
    "Quote": "Sitata",
    "Code": "Kod",
    "Insert": "Goý",
    "Embed": "Ornaşdyr",
    "Attach": "Goş",
    "Detach": "Aýyr",
    "Replace": "Çalyş",
    "Find": "Tap",
    "Undo": "Yza al",
    "Redo": "Gaýtala",
    "History": "Geçmiş",
    "Log": "Gündelik",
    "Record": "Ýazga al",
    "Play": "Oýnat",
    "Pause": "Arakesme",
    "Resume": "Dowam et",
    "Mute": "Sesini öçür",
    "Unmute": "Sesini aç",
    "Volume": "Ses derejesi",
    "Speed": "Tizlik",
    "Quality": "Hil",
    "Subtitles": "Subtitler",
    "Captions": "Ýazgylar",
    "Transcript": "Transkript",
    "Annotation": "Bellik",
    "Highlight": "Belläň",
    "Bookmark": "Bellik goý",
    "Favorite": "Halaýan",
    "Like": "Halaýaryn",
    "Dislike": "Halamaýaryn",
    "Subscribe": "Ýazyl",
    "Unsubscribe": "Ýazgydan çyk",
    "Follow": "Yzarla",
    "Unfollow": "Yzarlamagy bes et",
    "Invite": "Çagyr",
    "Join": "Goşul",
    "Leave": "Çyk",
    "Archive": "Arhiw",
    "Restore": "Dikelt",
    "Trash": "Zibil",
    "Permanent": "Hemişelik",
    "Temporary": "Wagtlaýyn",
    "Draft": "Garalama",
    "Published": "Neşir edilen",
    "Scheduled": "Meýilleşdirilen",
    "Pending": "Garaşylýar",
    "Approved": "Tassyklanan",
    "Rejected": "Ret edilen",
    "Completed": "Tamamlanan",
    "In progress": "Dowam edýär",
    "Not started": "Başlanmadyk",
    "Overdue": "Möhleti geçen",
    "Upcoming": "Geljekki",
    "Past": "Geçen",
    "Today": "Şugün",
    "Yesterday": "Düýn",
    "Tomorrow": "Ertir",
    "This week": "Şu hepde",
    "Last week": "Geçen hepde",
    "Next week": "Indiki hepde",
    "This month": "Şu aý",
    "Last month": "Geçen aý",
    "Next month": "Indiki aý",
    "This year": "Şu ýyl",
    "Last year": "Geçen ýyl",
    "Next year": "Indiki ýyl",
    "Never": "Hiç haçan",
    "Always": "Hemişe",
    "Sometimes": "Käte",
    "Often": "Köplenç",
    "Rarely": "Seýrek",
    "Frequently": "Ýygy-ýygydan",
    "Daily": "Gündelik",
    "Weekly": "Hepdelik",
    "Monthly": "Aýlyk",
    "Yearly": "Ýyllyk",
    "Once": "Bir gezek",
    "Twice": "Iki gezek",
    "Multiple": "Köp",
    "Single": "Ýeke",
    "Double": "Goşa",
    "Triple": "Üç esse",
    "First": "Birinji",
    "Second": "Ikinji",
    "Third": "Üçünji",
    "Last": "Soňky",
    "Current": "Häzirki",
    "Empty": "Boş",
    "Full": "Doly",
    "Partial": "Bölekleýin",
    "Complete": "Doly",
    "Incomplete": "Doly däl",
    "Valid": "Dogry",
    "Invalid": "Nädogry",
    "Correct": "Dogry",
    "Incorrect": "Nädogry",
    "True": "Dogry",
    "False": "Ýalňyş",
    "Passed": "Geçdi",
    "Failed": "Başartmady",
    "Minimum": "Iň az",
    "Maximum": "Iň köp",
    "Average": "Ortaça",
    "Ascending": "Ýokarlanýan",
    "Descending": "Aşaklaýan",
    "Alphabetical": "Elipbiý",
    "Numerical": "San",
    "Chronological": "Kronologik",
    "Random": "Tötänleýin",
    "Custom": "Ýörite",
    "Automatic": "Awtomatik",
    "Manual": "El bilen",
    "Both": "Ikisi hem",
    "Either": "Birinjisinden birisi",
    "Neither": "Hiç biri",
    "And": "We",
    "Or": "Ýa-da",
    "Not": "Däl",
    "If": "Eger",
    "Then": "Soň",
    "Else": "Ýogsam",
    "When": "Haçan",
    "Where": "Nirede",
    "Who": "Kim",
    "What": "Näme",
    "Why": "Näme üçin",
    "How": "Nädip",
    "Which": "Haýsy",
    "Whose": "Kimiň",
    "Moodle": "Moodle",
    "Eduvestra": "Eduvestra",
    "campus.example.edu": "eduvestra.com",
}

def translate_text(text):
    """Translate English text to Turkmen"""
    if not isinstance(text, str):
        return text

    # Skip if already translated or empty
    if not text or text == "":
        return text

    # Keep HTML tags, placeholders intact
    # Don't translate if it's a technical term or already has Turkmen characters

    result = text

    # Replace Moodle with Eduvestra in appropriate contexts
    result = result.replace("Moodle App", "Eduvestra")
    result = result.replace("Moodle app", "Eduvestra")
    result = result.replace("Moodle Mobile", "Eduvestra")
    result = result.replace("Moodle mobile", "Eduvestra")
    result = result.replace("campus.example.edu", "eduvestra.com")

    # For now, return as is - we'll use the existing translations as base
    # and manually create comprehensive translations
    return result

# For this large translation task, we'll need to manually translate
# Let's create a comprehensive translation by extending the existing tk.json

print(f"Total English entries: {len(en_data)}")
print(f"Existing Turkmen entries: {len(tk_data)}")
print(f"Missing translations: {len(en_data) - len(tk_data)}")

# Save this info for reference
with open('/Users/merdana/AndroidStudioProjects/eduvesta/translation_stats.txt', 'w', encoding='utf-8') as f:
    f.write(f"Total English entries: {len(en_data)}\n")
    f.write(f"Existing Turkmen entries: {len(tk_data)}\n")
    f.write(f"Missing translations: {len(en_data) - len(tk_data)}\n\n")
    f.write("Missing keys:\n")
    for key in sorted(en_data.keys()):
        if key not in tk_data:
            f.write(f"  {key}: {en_data[key][:100]}\n")
